### ISSUE TITLE
Identity does not implements TenantInteface

### ISSUE THREAD

**Issue by amismailz** [solutosoft/yii-multitenant#2]
Hello! Thank you so mucj for this helpful extension.

I get this error and the below code is the cause:

```
/**
     * Adds an additional WHERE tenant condition to the existing one.
     * @return void
     */
    private function addTenantCondition()
    {
        $identity = Yii::$app->user->identity;
        if ($identity instanceof TenantInterface) {
            list(,$alias) = $this->getTableNameAndAlias();
            $this->andOnCondition(["{$alias}.tenant_id" => $identity->getTenantId()]);
        } else if (Yii::$app instanceof WebApplication) {
            throw new NotSupportedException("Identity does not implements TenantInteface");
        }
    }
```

This error appears while Yii is trying to get the identity instance, so the identity is not loaded yet, so this condition fails as `Yii::$app->user->identity` is NULL;

Below is the stack trace:

```
yii\base\NotSupportedException: Identity does not implements TenantInteface in /var/www/html/mt_alraheem/_protected/vendor/solutosoft/yii-multitenant/src/MultiTenantQuery.php:59
Stack trace:
#0 /var/www/html/mt_alraheem/_protected/vendor/solutosoft/yii-multitenant/src/MultiTenantQuery.php(20): solutosoft\multitenant\MultiTenantQuery->addTenantCondition()
#1 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/db/QueryBuilder.php(227): solutosoft\multitenant\MultiTenantQuery->prepare()
#2 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/db/ActiveQuery.php(328): yii\db\QueryBuilder->build()
#3 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/db/Query.php(285): yii\db\ActiveQuery->createCommand()
#4 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/db/ActiveQuery.php(304): yii\db\Query->one()
#5 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveQuery->one()
#6 /var/www/html/mt_alraheem/_protected/common/models/UserIdentity.php(70): yii\db\BaseActiveRecord::findOne()
#7 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/web/User.php(692): common\models\UserIdentity::findIdentity()
#8 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/web/User.php(194): yii\web\User->renewAuthStatus()
#9 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/web/User.php(362): yii\web\User->getIdentity()
#10 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#11 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2-debug/src/panels/UserPanel.php(83): yii\base\Component->__get()
#12 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\panels\UserPanel->init()
#13 [internal function]: yii\base\BaseObject->__construct()
#14 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs()
#15 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build()
#16 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#17 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2-debug/src/Module.php(247): yii\BaseYii::createObject()
#18 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2-debug/src/Module.php(218): yii\debug\Module->initPanels()
#19 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\Module->init()
#20 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct()
#21 [internal function]: yii\base\Module->__construct()
#22 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/di/Container.php(398): ReflectionClass->newInstanceArgs()
#23 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build()
#24 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get()
#25 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject()
#26 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/Application.php(315): yii\base\Module->getModule()
#27 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#28 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/Application.php(273): yii\web\Application->bootstrap()
#29 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\base\Application->init()
#30 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct()
#31 /var/www/html/mt_alraheem/backend/index.php(18): yii\base\Application->__construct()
#32 {main}
```

**Comment by leandrogehlen** [comment]
This is happening, because the user is guest.
If you need to execute a query when user is guest, you need use `UserIdentity::withoutTenant()`.

Looking at your stack
`#7 /var/www/html/mt_alraheem/_protected/vendor/yiisoft/yii2/web/User.php(692): common\models\UserIdentity::findIdentity()` i belive this method is the problem

the method should be something like: 

```php
public static function findIdentity($id)
{
        return static::find()
            ->withoutTenant()
            ->where(['id' => $id])
            ->one();
}
```

**Comment by amismailz** [comment]
Nope, user is already logged in but Yii is calling renewAuthStatus()  _(To update the authentication status using the information from session and cookie)_ this function calls `findIdentity($id)` method in the identity class:

```
/**
     * Finds an identity by the given ID.
     *
     * @param  int|string $id The user id.
     * @return IdentityInterface|static
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => User::STATUS_ACTIVE]);
    }
```

So the condition fails at this point. Can I edit the above query to use `withoutTenant()` ?

**Comment by leandrogehlen** [comment]
Please, try it

```php
public static function findIdentity($id)
{
        return static::find()
            ->withoutTenant()
            ->where(['id' => $id, 'status' => User::STATUS_ACTIVE])
            ->one();
}

**Comment by amismailz** [comment]
That did the trick! very strait forward solution.

Thank you so much :)
